### ISSUE TITLE
Support positive and negative signs on numbers

### ISSUE THREAD

**Issue by tusharsadhwani** [tusharsadhwani/json5-rt#10]
`+1` is a valid json5 literal, and `-1.3` as well.

**Comment by Agent-Hellboy** [comment]
Didn't we need -1, 
Should we follow this inheritance tree and add a new node for -ve and +ve and -ve and -ve infinity and Nan?
https://spec.json5.org/#numbers
```
[JSON5Number]
      [JSON5NumericLiteral]
    +[JSON5NumericLiteral]
     -[JSON5NumericLiteral]
    
[JSON5NumericLiteral]
      [NumericLiteral]
      Infinity
      NaN
 ```

**Comment by tusharsadhwani** [comment]
Not necessarily. As long as it's parseable to valid json it doesn't matter how we keep the tree
