### ISSUE TITLE
Node.replace doesn't seem to work for a non-nested string

### ISSUE THREAD

**Issue by eugenesvk** [tusharsadhwani/json5-rt#7]
I'm trying to understand why `node.replace()` works when I visit a string within an array, but fails when I visit a string within a string?
The `replace` call within `Json5Primitive` fires in both cases and returns the replacement string.
Or is this precisely because one is a child of an array and another is not???

I basically follow your advice from https://github.com/tusharsadhwani/json5kit/issues/3 and store only the nodes that match some condition in a dictionary (in this example the condition is a) object and b) its key is `"keys"`)
And then I iterate with a `generic_visit` which fires up the replacement only if the object is in a dictionary.

```py
def replaceJsonString():
  import json5kit
  from json5kit import Json5Node, Json5Array, Json5String, Json5Object

  source_work = R"""[{"keys":["a"]}]""" # THIS WORKS
    # bef="a"
    # aft="×××"
    # [{"keys":["×××"]}]
  source_fail = R"""[{"keys":"a"}]""" # THIS FAILS
    # bef="a"
    # aft="×××"
    # [{"keys":"a"}]
  tree = json5kit.parse(source_work)
  # tree = json5kit.parse(source_fail)

  class letterTransformer(json5kit.Json5Transformer):
    def visit_String(self, node):
      ret = node.replace('"×××"')
      print(f"bef={node.to_source()}\naft={ret.to_source()}")
      return ret
  class DictTransformer(json5kit.Json5Transformer):
    def __init__(self):
      self.object_value_to_key = {}
    def visit_Object(self, node):
      for key, val in zip(node.keys, node.values):
        if key.value.value == "keys":
          self.object_value_to_key[val] = key
      super().generic_visit(node)
      return node

    def generic_visit(self, node):
      super().generic_visit(node)
      if (key := self.object_value_to_key.get(node)):
        letterTransformer().visit(node)
      return node
  print(tree.to_source())
  DictTransformer().visit(tree)
  print(tree.to_source())

replaceJsonString()
```

**Comment by tusharsadhwani** [comment]
you're missing a return.

```diff
if (key := self.object_value_to_key.get(node)):
-    letterTransformer().visit(node)
+    return letterTransformer().visit(node)
```

visit by itself won't edit the node in place. you have to return the modified node.

**Comment by tusharsadhwani** [comment]
This also works:
```diff
if (key := self.object_value_to_key.get(node)):
-    letterTransformer().visit(node)
+    node = letterTransformer().visit(node)
```

**Comment by eugenesvk** [comment]
Oh, I thought the next line with `return node` dealt with it, but I see the recursive errors of my ways (I like your second example more with just one return and then modifiers to node along the way)
Thanks a bunch!

(in general, I think it might be nice if the node manipulation could be more direct instead of having to parse it once to save the structure and then parse it twice to manipulate if it matches the structure)

**Comment by tusharsadhwani** [comment]
> instead of having to parse it once to save the structure and then parse it twice to manipulate if it matches the structure

It's not being parsed twice, thankfully. It is being iterated on twice, but that is very common amongst node manipulating visitor patterns. I am yet to figure out a better way to do this.
